### PR TITLE
Continuous Delivery fix

### PR DESCRIPTION
**Pull request by CaeNGnp**
Related: #33

### CODE REVIEW

**Comment by CaeNGnp** [comment]
Upload artifacts needs to be changed to releases (see https://github.com/actions/create-release). I will push one more patch for that and @kenwongz / @jordie007 you may take care of the remaining work thereafter to fit discussed requirements

**Comment by CaeNGnp** [comment]
> Upload artifacts needs to be changed to releases (see https://github.com/actions/create-release). I will push one more patch for that and @kenwongz / @jordie007 you may take care of the remaining work thereafter to fit discussed requirements

Moving to [`softprops/action-gh-release`](https://github.com/softprops/action-gh-release) as `actions/create-release` is now unmaintained and does not support attaching assets

**Comment by CaeNGnp** [comment]
All should be good on the compilation/uploading end, passing it on to @kenwongz to update the rest

**Comment by kenwongz** [comment]
@jordie007 Please create a test release

**Review by kenwongz — APPROVED** [review]

**Review by jordie007 — APPROVED** [review]
Test release has been created as per the request from @CaeNGnp and @kenwongz.

**Comment by CaeNGnp** [comment]
^ [`v1.0.0-test`](https://github.com/kenwongz/SimpCity/releases/tag/v1.0.0-test)

**Pull request merged**
