### PR TITLE
City size configuration; Bug fixes

### LINKED ISSUE #29: US-15: As a player, I want to choose the city size to play in so that I can challenge myself across different map sizes
> - Note that you will have to adjust the number of available buildings appropriately for all the different city sizes.
> - There will also be a limit to the size of the city in relation to the number of choices.

- Develop logic
- Develop view

To discuss:
- Calculate remaining buildings dynamically
- Max grid size

### PR DESCRIPTION
**Pull request by CaeNGnp**
### 1. City size config
This changeset adds a configuration to allow the player to change the city size.

image

- Resolves #29 

### 2, Fix leaderboard bug
Fixes a bug with giving empty/>20 chars name in leaderboard.

P.S. As per request, made this PR from a local branch rather than a fork to facilitate easier testing from VS.

### CODE REVIEW

**Comment by CaeNGnp** [comment]
Needs a basic test to test city grid boundaries, i.e. `BuildAt_ThrowsException_WhenOutOfBoundsAndCustomSize`.

**Comment by CaeNGnp** [comment]
The latest set of commits
- Adds limit to city size (10x10) #29
- Scale building copies with formula #29
- Fix a bug with giving empty/>20 chars name in leaderboard

**Review by kenwongz — APPROVED** [review]
tested and looks good

**Review by JSQJ — APPROVED** [review]
no issues

**Pull request merged**
