### PR TITLE
Monument point scoring

### LINKED ISSUE #48: US-13a: As a player, I want to be assigned a score for placing each "monuments" so that I can get point

### PR DESCRIPTION
**Pull request by Harish110**
First part of scoring has been done

### CODE REVIEW

**Comment by kenwongz** [comment]
What does the first part contains?

**Comment by CaeNGnp** [comment]
I believe it's everything except this
> However, if there are at least 3 monuments in the city that are built on corner squares, then all monuments score 4 points each (including those that are not built on
corner squares)

Which would require another separate check on the grid at the corners to determine the score for all monuments

**Comment by kenwongz** [comment]
@Harish110 how is this progress?

**Comment by Harish110** [comment]
> @Harish110 how is this progress?

@kenwongz Still stuck for 1 more part which is 3 monuments built on corner

**Review by kenwongz — APPROVED** [review]
Tested and working

**Review by JSQJ — APPROVED** [review]
tested ok

**Review by CaeNGnp — APPROVED** [review]
Stated requirement works but will need to keep track of the missing requirement

**Pull request merged**
