### PR TITLE
Fix for saving functionality

### LINKED ISSUE #2: US-3: As a player, I want to be able to save my current game so that I can continue at a later time

### PR DESCRIPTION
**Pull request by CaeNGnp**
Resolves #2 
Related: #3 

This patch actually implements the saving functionality, taking into account saving multiple times in the same session (thanks @kenwongz for pointing out).

### CODE REVIEW

**Comment by CaeNGnp** [comment]
For @Harish110 to ack – this PR modifies your portion on `Game.Restore`, in case you have a staging patch that conflicts.

https://github.com/kenwongz/SimpCity/pull/54/files#diff-9247e358238b67aa1259ce859ad724508b1338835778c92553b6ba376bb7882aR310-R322

**Review by kenwongz — APPROVED** [review]
Tested

**Review by JSQJ — APPROVED** [review]
Issues fixed

**Review by jordie007 — APPROVED** [review]
Code looks good to me. Issue has been approved

**Pull request merged**
